// settlement.js - revamped to use flat tags array

const AREA_TAGS = {
  'aberdeen city council': ['northeast', 'grampian', 'east coast'],
  'aberdeenshire council': ['northeast', 'grampian'],
  'angus council': ['tayside', 'east coast'],
  'argyll and bute council': ['west coast'],
  'clackmannanshire council': ['forth valley'],
  'dumfries and galloway council': ['borders'],
  'dundee city council': ['northeast', 'east coast', 'tayside'],
  'east ayrshire council': ['ayrshire', 'west coast'],
  'east dunbartonshire council': ['central belt'],
  'east renfrewshire council': ['central belt'],
  'east lothian council': ['central belt', 'east coast'],
  'edinburgh city council': ['central belt', 'east coast'],
  'falkirk council': ['forth valley', 'central belt'],
  'fife council': ['fife', 'east coast', 'central belt'],
  'glasgow city council': ['central belt', 'west coast'],
  'highland council': ['highlands'],
  'inverclyde council': ['west coast'],
  'midlothian council': ['central belt'],
  'moray council': ['northeast'],
  'western isles': ['islands', 'west coast'],
  'north ayrshire council': ['ayrshire', 'west coast'],
  'north lanarkshire council': ['central belt'],
  'orkney islands council': ['islands'],
  'perth and kinross council': ['tayside'],
  'renfrewshire council': ['west coast'],
  'scottish borders council': ['borders'],
  'shetland islands council': ['islands'],
  'south ayrshire council': ['ayrshire', 'west coast'],
  'south lanarkshire council': ['central belt'],
  'stirling council': ['forth valley'],
  'west dunbartonshire council': ['west coast'],
  'west lothian council': ['central belt', 'east coast']
};

export default (rawSettlements => {
  return rawSettlements.map(s => {
    const tags = [];
    tags.push(s.status);
    tags.push(s.council.toLowerCase());
    tags.push(s.geography_type);
    tags.push(s.region.toLowerCase());
    const area = AREA_TAGS[s.council.toLowerCase()];
    if (area) tags.push(...area);
    return {
      name: s.name,
      population: s.population,
      tags: Array.from(new Set(tags))
    };
  });
})([
  //AREAS//
   { name: 'anderston', status: 'area', population: 7400, council: 'glasgow city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'anniesland', status: 'area', population: 9100, council: 'glasgow city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'govan', status: 'area', population: 11400, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'hillhead', status: 'area', population: 10500, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'maryhill', status: 'area', population: 18200, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'parkhead', status: 'area', population: 9400, council: 'glasgow city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'partick', status: 'area', population: 21000, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'pollokshields', status: 'area', population: 24000, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'shettleston', status: 'area', population: 15000, council: 'glasgow city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'springburn', status: 'area', population: 16500, council: 'glasgow city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },

  { name: 'leith', status: 'area', population: 13000, council: 'edinburgh city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'new town', status: 'area', population: 20500, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'old town', status: 'area', population: 10400, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'morningside', status: 'area', population: 13300, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'portobello', status: 'area', population: 14000, council: 'edinburgh city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'stockbridge', status: 'area', population: 5200, council: 'edinburgh city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'dean village', status: 'area', population: 1500, council: 'edinburgh city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'gorgie', status: 'area', population: 13300, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'corstorphine', status: 'area', population: 18400, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'haymarket', status: 'area', population: 3800, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },

  { name: 'altens', status: 'area', population: 4000, council: 'aberdeen city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'bridge of don', status: 'area', population: 11800, council: 'aberdeen city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'dyce', status: 'area', population: 10500, council: 'aberdeen city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'old aberdeen', status: 'area', population: 5500, council: 'aberdeen city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'torry', status: 'area', population: 11500, council: 'aberdeen city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },

  { name: 'broughty ferry', status: 'area', population: 13000, council: 'dundee city council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'dundee city centre', status: 'area', population: 15000, council: 'dundee city council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'downfield', status: 'area', population: 5000, council: 'dundee city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'lochee', status: 'area', population: 12000, council: 'dundee city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },
  { name: 'ninewells', status: 'area', population: 3500, council: 'dundee city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: null },

  { name: 'dunfermline', status: 'city', population: 55000, council: 'fife council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'stirling', status: 'city', population: 38000, council: 'stirling council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'perth', status: 'city', population: 47000, council: 'perth and kinross council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'inverness', status: 'city', population: 48000, council: 'highland council', geography_type: 'on river', region: 'Highlands', has_uni: true, largest_settlement: true },
  { name: 'edinburgh', status: 'city', population: 530000, council: 'edinburgh city council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'glasgow', status: 'city', population: 620000, council: 'glasgow city council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'aberdeen', status: 'city', population: 230000, council: 'aberdeen city council', geography_type: 'on river', region: 'Highlands', has_uni: true, largest_settlement: true },
  { name: 'dundee', status: 'city', population: 148000, council: 'dundee council', geography_type: 'coastal', region: 'Central Belt', has_uni: true, largest_settlement: true },

  { name: 'east kilbride', status: 'new town', population: 75000, council: 'south lanarkshire council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'livingston', status: 'new town', population: 57000, council: 'west lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'cumbernauld', status: 'new town', population: 51000, council: 'north lanarkshire council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'irvine', status: 'new town', population: 34000, council: 'north ayrshire council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: true },

  { name: 'paisley', status: 'town', population: 77000, council: 'renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'hamilton', status: 'town', population: 54000, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'kirkcaldy', status: 'town', population: 60200, council: 'fife council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'kilmarnock', status: 'town', population: 47000, council: 'east ayrshire council', geography_type: 'on river', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'ayr', status: 'town', population: 46000, council: 'south ayrshire council', geography_type: 'coastal', region: 'Central Belt', has_uni: true, largest_settlement: true },
  { name: 'coatbridge', status: 'town', population: 44000, council: 'north lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'greenock', status: 'town', population: 41000, council: 'inverclyde council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'glenrothes', status: 'town', population: 38000, council: 'fife council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'airdrie', status: 'town', population: 36000, council: 'north lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'motherwell', status: 'town', population: 33000, council: 'north lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'rutherglen', status: 'town', population: 31000, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'cambuslang', status: 'town', population: 31000, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'wishaw', status: 'town', population: 30000, council: 'north lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'bearsden', status: 'town', population: 28000, council: 'east dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'newton mearns', status: 'town', population: 28000, council: 'east renfrewshire council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'clydebank', status: 'town', population: 26000, council: 'west dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'elgin', status: 'town', population: 25000, council: 'moray council', geography_type: 'landlocked', region: 'Highlands', has_uni: false, largest_settlement: true },
  { name: 'renfrew', status: 'town', population: 24000, council: 'renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'bishopbriggs', status: 'town', population: 24000, council: 'east dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'bathgate', status: 'town', population: 24000, council: 'west lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'arbroath', status: 'town', population: 24000, council: 'angus council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'kirkintilloch', status: 'town', population: 22000, council: 'east dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'musselburgh', status: 'town', population: 21000, council: 'east lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'dumbarton', status: 'town', population: 20000, council: 'west dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'bellshill', status: 'town', population: 20000, council: 'north lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'peterhead', status: 'town', population: 19000, council: 'aberdeenshire council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'st andrews', status: 'town', population: 18000, council: 'fife council', geography_type: 'coastal', region: 'Central Belt', has_uni: true, largest_settlement: false },
  { name: 'bonnyrigg', status: 'town', population: 18000, council: 'midlothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'barrhead', status: 'town', population: 18000, council: 'east renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'blantyre', status: 'town', population: 17000, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'penicuik', status: 'town', population: 16000, council: 'midlothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'grangemouth', status: 'town', population: 16000, council: 'falkirk council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'kilwinning', status: 'town', population: 16000, council: 'north ayrshire council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'broxburn', status: 'town', population: 16000, council: 'west lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'johnstone', status: 'town', population: 16000, council: 'renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'viewpark', status: 'town', population: 16000, council: 'north lanarkshire council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'larkhall', status: 'town', population: 15000, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'erskine', status: 'town', population: 15000, council: 'renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },

  { name: 'callander', status: 'market town', population: 3156, council: 'stirling council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'crieff', status: 'market town', population: 7990, council: 'perth and kinross council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'aberfeldy', status: 'market town', population: 1886, council: 'perth and kinross council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'kelso', status: 'market town', population: 6000, council: 'scottish borders council', geography_type: 'landlocked', region: 'Borders', has_uni: false, largest_settlement: false },
  { name: 'jedburgh', status: 'market town', population: 5200, council: 'scottish borders council', geography_type: 'landlocked', region: 'Borders', has_uni: false, largest_settlement: false },
  { name: 'innerleithen', status: 'market town', population: 3152, council: 'scottish borders council', geography_type: 'landlocked', region: 'Borders', has_uni: false, largest_settlement: false },
  { name: 'haddington', status: 'market town', population: 11354, council: 'east lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'lanark', status: 'market town', population: 8500, council: 'south lanarkshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'peebles', status: 'market town', population: 8000, council: 'scottish borders council', geography_type: 'on river', region: 'Borders', has_uni: false, largest_settlement: false },

  { name: 'galston', status: 'town', population: 13300, council: 'east ayrshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'kirkwall', status: 'town', population: 9000, council: 'orkney islands council', geography_type: 'coastal', region: 'Islands', has_uni: false, largest_settlement: true },
  { name: 'stromness', status: 'town', population: 2300, council: 'orkney islands council', geography_type: 'coastal', region: 'Islands', has_uni: false, largest_settlement: false },
  { name: 'lerwick', status: 'town', population: 7000, council: 'shetland islands council', geography_type: 'coastal', region: 'Islands', has_uni: false, largest_settlement: true },
  { name: 'stornoway', status: 'town', population: 6700, council: 'outer hebrides council', geography_type: 'coastal', region: 'Islands', has_uni: true, largest_settlement: true },
  { name: 'mallaig', status: 'town', population: 3100, council: 'highland council', geography_type: 'coastal', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'kirriemuir', status: 'town', population: 13000, council: 'angus council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'lochwinnoch', status: 'town', population: 4000, council: 'renfrewshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'armadale', status: 'town', population: 13000, council: 'west lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'silverknowes', status: 'area', population: 2000, council: 'edinburgh city council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'blackburn', status: 'town', population: 6000, council: 'west lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false},
  { name: 'uphall', status: 'town', population: 5000, council: 'west lothian council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'helensburgh', status: 'town', population: 15000, council: 'argyll and bute council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: true },
  { name: 'north berwick', status: 'town', population: 7600, council: 'east lothian council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'westhill', status: 'town', population: 12000, council: 'aberdeenshire council', geography_type: 'landlocked', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'whitburn', status: 'town', population: 15000, council: 'west lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'fauldhouse', status: 'town', population: 4800, council: 'west lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'annan', status: 'town', population: 8900, council: 'dumfries and galloway council', geography_type: 'coastal', region: 'Borders', has_uni: false, largest_settlement: false },
  { name: 'arbroath', status: 'town', population: 23800, council: 'angus council', geography_type: 'coastal', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'alexandria', status: 'town', population: 6700, council: 'west dunbartonshire council', geography_type: 'on river', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'buckie', status: 'town', population: 8400, council: 'moray council', geography_type: 'coastal', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'carnoustie', status: 'town', population: 10700, council: 'angus council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'dalkeith', status: 'town', population: 11600, council: 'midlothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: true, largest_settlement: false },
  { name: 'dunbar', status: 'town', population: 8600, council: 'east lothian council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'ellon', status: 'town', population: 8600, council: 'aberdeenshire council', geography_type: 'landlocked', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'forres', status: 'town', population: 8500, council: 'moray council', geography_type: 'landlocked', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'gretna', status: 'town', population: 3000, council: 'dumfries and galloway council', geography_type: 'landlocked', region: 'Borders', has_uni: false, largest_settlement: false },
  { name: 'haddington', status: 'town', population: 8800, council: 'east lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'inverurie', status: 'town', population: 9600, council: 'aberdeenshire council', geography_type: 'landlocked', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'kirkintilloch', status: 'town', population: 20000, council: 'east dunbartonshire council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'largs', status: 'town', population: 10900, council: 'north ayrshire council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'montrose', status: 'town', population: 11400, council: 'angus council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'penicuik', status: 'town', population: 16000, council: 'midlothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'stonehaven', status: 'town', population: 9400, council: 'aberdeenshire council', geography_type: 'coastal', region: 'Highlands', has_uni: false, largest_settlement: false },
  { name: 'thurso', status: 'town', population: 8500, council: 'highland council', geography_type: 'coastal', region: 'Highlands', has_uni: true, largest_settlement: false },
  { name: 'prestonpans', status: 'town', population: 10400, council: 'east lothian council', geography_type: 'coastal', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'gorebridge', status: 'town', population: 8900, council: 'midlothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'linlithgow', status: 'town', population: 13000, council: 'west lothian council', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settlement: false },
  { name: 'coatbridge', status: 'town', population: 44000, council: 'north lanarkshire', geography_type: 'landlocked', region: 'Central Belt', has_uni: false, largest_settllement: false }
]);
